=== ehasting/GoScope-RepoGenerator/device.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.scopeportal.com/device"
           xmlns="http://www.scopeportal.com/device"
           elementFormDefault="qualified">
    
    <xs:element name="device">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="base">
                    <xs:complexType>
                        <xs:attribute name="id" type="UUID-random" />
                        <xs:attribute name="author" type="xs:string" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="version">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="release-notes" type="xs:string"/>
                            <xs:element name="file-set">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="file" type="xs:string" maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="number" type="xs:decimal" />
                        <xs:attribute name="filename" type="xs:string" />
                        <xs:attribute name="added" type="xs:dateTime" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="displayname" type="xs:string"/>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="category" type="xs:string"/>
                <xs:element name="tags" type="tags-tag" />
                <xs:element name="site" type="xs:string"/>
                <xs:element name="media" type="media-tag" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="tags-tag">
        <xs:sequence>
            <xs:element name="tag" type="tag-tag" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tag-tag">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="media-tag">
        <xs:sequence>
            <xs:element name="file" type="file-tag" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="file-tag">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" type="xs:string" />
                <xs:attribute name="mime" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>


    <xs:simpleType name="UUID-random">
        <xs:restriction base="xs:string">
            <xs:length value="36" fixed="true" />
            <xs:pattern value="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== ehasting/GoScope-RepoGenerator/device.xml
<?xml version="1.0" encoding="UTF-8"?>
<device xmlns="http://www.scopeportal.com/device"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.scopeportal.com/device device.xsd">
    <base id="8F6476B0-608C-11E2-BCFD-0800200C9A66" author="niceboy"/>
    <version number="2.6" filename="jb            cv.zip" added="2013-01-04T09:02:04">
        <release-notes>New attack and decay feature</release-notes>
        <file-set>
            <file>blah.dev</file>
            <file>blah.pre</file>
            <file>blah.dll</file>
        </file-set>
    </version>
    <displayname>Another Device 2.0</displayname>
    <description>Stereo Transient Shaper - Dante:  And your design goals for BassSynthi?
        Roy: After DxSynth and Atze, I wanted to make a compact, easy-to-edit synth device, which nevertheless should have a distinctive sound.  By fiddling around with the Modular Synth, I found a simple way to realize Phase Modulation. Osc1 goes to a Modulation Delay, which delay time is being modulated by Osc2.  The output of both oscillators is summed, passed though envelopes, an LFO, a low pass filter and finally the effects insert and thatâ€™s it!</description>
    <category>Effects/Stereo/Dynamics</category>
    <tags>
        <tag type="subcategory">Transient Shaper</tag>
        <tag type="status">Active</tag>
        <tag type="dsp-requirement">Low</tag>
    </tags>
    <site>http://forums.planetz.com/viewtopic.php?f=16&amp;t=28778</site>
    <media>
        <file mime="audio/mp3" type="repo-path">hey.mp3</file>
        <file mime="image/jpg" type="url">http://www.scopeportal.com/wp-content/uploads/2012/03/CwMix16-161.jpg</file>
        <file mime="image/jpg" type="url">http://www.scopeportal.com/wp-content/uploads/2012/03/le-1.jpg</file>
        <file mime="application/pdf" type="repo-path">anotherdevice/user-manual.pdf</file>
    </media>
</device>
